apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: demo
    image: 820242905231.dkr.ecr.ap-southeast-1.amazonaws.com/bookinfo/bookinfo-productpage-v1:1.20.3
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80