apiVersion: v1
kind: Pod
metadata:
  name: productpage
spec:
  containers:
  - name: productpage
    image: 820242905231.dkr.ecr.ap-southeast-1.amazonaws.com/bookinfo/bookinfo-productpage-v1:1.20.3
  imagePullSecrets:
  - name: my-secret